name: Trivy Scan Image
on:
  workflow_call:
    inputs:
      images:
        description: Image to Scan
        required: true
        type: string
jobs:
  build:
    name: CVE Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ inputs.image }}
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}